create extension if not exists postgis;
create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  display_name text,
  avatar_url text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  location_geo geography(point, 4326),
  city text,
  country text,
  loop_points integer not null default 0,
  trust_score numeric(3,2) not null default 5.0,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  label text not null,
  parent_slug text references public.categories(slug),
  co2_factor_per_kg numeric not null default 0.5,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  donor_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  category_slug text not null references public.categories(slug),
  quantity_kg numeric not null check (quantity_kg > 0),
  photo_url text,
  pickup_address text,
  pickup_geo geography(point, 4326),
  pickup_window_start timestamptz,
  pickup_window_end timestamptz,
  is_recurring boolean not null default false,
  recurrence_pattern text,
  status text not null default 'open' check (status in ('open', 'claimed', 'completed', 'expired')),
  claimed_by uuid references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  category_slug text not null references public.categories(slug),
  quantity_kg_min numeric check (quantity_kg_min is null or quantity_kg_min > 0),
  quantity_kg_max numeric check (quantity_kg_max is null or quantity_kg_max > 0),
  frequency text default 'one-time',
  pickup_geo geography(point, 4326),
  max_distance_km numeric not null default 10 check (max_distance_km > 0),
  status text not null default 'open' check (status in ('open', 'fulfilled', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete set null,
  request_id uuid references public.requests(id) on delete set null,
  donor_id uuid not null references public.users(id) on delete cascade,
  recipient_id uuid not null references public.users(id) on delete cascade,
  kg_diverted numeric not null check (kg_diverted > 0),
  co2_saved_kg numeric,
  water_saved_liters numeric,
  donor_rating smallint check (donor_rating between 1 and 5),
  recipient_rating smallint check (recipient_rating between 1 and 5),
  donor_review text,
  recipient_review text,
  completed_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null,
  title text,
  body text,
  listing_id uuid references public.listings(id) on delete set null,
  request_id uuid references public.requests(id) on delete set null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists listings_pickup_geo_idx on public.listings using gist (pickup_geo);
create index if not exists listings_open_category_idx on public.listings (category_slug) where status = 'open';
create index if not exists requests_pickup_geo_idx on public.requests using gist (pickup_geo);
create index if not exists requests_open_category_idx on public.requests (category_slug) where status = 'open';
create index if not exists notifications_user_created_idx on public.notifications (user_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    display_name = coalesce(excluded.display_name, public.users.display_name),
    avatar_url = coalesce(excluded.avatar_url, public.users.avatar_url),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.find_matching_requests(
  p_category text,
  p_geo geography,
  p_quantity numeric
)
returns table (
  id uuid,
  requester_id uuid,
  title text,
  category_slug text,
  quantity_kg_min numeric,
  quantity_kg_max numeric,
  max_distance_km numeric,
  distance_m double precision,
  created_at timestamptz
)
language sql
stable
as $$
  select
    r.id,
    r.requester_id,
    r.title,
    r.category_slug,
    r.quantity_kg_min,
    r.quantity_kg_max,
    r.max_distance_km,
    st_distance(r.pickup_geo, p_geo) as distance_m,
    r.created_at
  from public.requests r
  where r.status = 'open'
    and (
      r.category_slug = p_category
      or exists (
        select 1
        from public.categories c
        where c.slug = p_category
          and c.parent_slug = r.category_slug
      )
    )
    and (r.quantity_kg_min is null or r.quantity_kg_min <= p_quantity)
    and (r.quantity_kg_max is null or r.quantity_kg_max >= p_quantity)
    and (
      p_geo is null
      or r.pickup_geo is null
      or st_dwithin(r.pickup_geo, p_geo, r.max_distance_km * 1000)
    )
  order by distance_m asc nulls last, r.created_at asc
  limit 5;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute procedure public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row execute procedure public.set_updated_at();

drop trigger if exists requests_set_updated_at on public.requests;
create trigger requests_set_updated_at
before update on public.requests
for each row execute procedure public.set_updated_at();

insert into public.categories (slug, label, parent_slug, co2_factor_per_kg)
values
  ('organic', 'Organic', null, 0.5),
  ('vegetable-scraps', 'Vegetable Scraps', 'organic', 0.5),
  ('fruit-waste', 'Fruit Waste', 'organic', 0.5),
  ('coffee-grounds', 'Coffee Grounds', 'organic', 0.5),
  ('tea-leaves', 'Tea Leaves', 'organic', 0.5),
  ('eggshells', 'Eggshells', 'organic', 0.5),
  ('bread-stale', 'Stale Bread', 'organic', 0.5),
  ('rice-cooked', 'Cooked Rice', 'organic', 0.5),
  ('fish-bones-shells', 'Fish Bones and Shells', 'organic', 0.5),
  ('meat-trimmings', 'Meat Trimmings', 'organic', 0.5),
  ('brewery-fermentation', 'Brewery and Fermentation', null, 0.5),
  ('spent-grain', 'Spent Grain', 'brewery-fermentation', 0.5),
  ('fruit-pomace', 'Fruit Pomace', 'brewery-fermentation', 0.5),
  ('whey', 'Whey', 'brewery-fermentation', 0.5),
  ('sourdough-discard', 'Sourdough Discard', 'brewery-fermentation', 0.5),
  ('yeast-slurry', 'Yeast Slurry', 'brewery-fermentation', 0.5),
  ('agricultural', 'Agricultural', null, 0.5),
  ('blemished-produce', 'Blemished Produce', 'agricultural', 0.5),
  ('crop-trimmings', 'Crop Trimmings', 'agricultural', 0.5),
  ('husks-bran', 'Husks and Bran', 'agricultural', 0.5),
  ('processing-by-products', 'Processing By-Products', null, 0.5),
  ('cooking-oil-used', 'Used Cooking Oil', 'processing-by-products', 0.5),
  ('food-processing-waste', 'Food Processing Waste', 'processing-by-products', 0.5),
  ('surplus-packaged-food', 'Surplus Packaged Food', 'processing-by-products', 0.5),
  ('other', 'Other', null, 0.5),
  ('compostable-packaging', 'Compostable Packaging', 'other', 0.5),
  ('garden-waste', 'Garden Waste', 'other', 0.5)
on conflict (slug) do update
set
  label = excluded.label,
  parent_slug = excluded.parent_slug,
  co2_factor_per_kg = excluded.co2_factor_per_kg;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.listings enable row level security;
alter table public.requests enable row level security;
alter table public.transactions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "users_select_self" on public.users;
create policy "users_select_self" on public.users
for select to authenticated
using (auth.uid() = id);

drop policy if exists "users_update_self" on public.users;
create policy "users_update_self" on public.users
for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "categories_read_authenticated" on public.categories;
create policy "categories_read_authenticated" on public.categories
for select to authenticated
using (true);

drop policy if exists "listings_read_authenticated" on public.listings;
create policy "listings_read_authenticated" on public.listings
for select to authenticated
using (true);

drop policy if exists "listings_insert_self" on public.listings;
create policy "listings_insert_self" on public.listings
for insert to authenticated
with check (auth.uid() = donor_id);

drop policy if exists "listings_update_owner" on public.listings;
create policy "listings_update_owner" on public.listings
for update to authenticated
using (auth.uid() = donor_id)
with check (auth.uid() = donor_id);

drop policy if exists "requests_read_authenticated" on public.requests;
create policy "requests_read_authenticated" on public.requests
for select to authenticated
using (true);

drop policy if exists "requests_insert_self" on public.requests;
create policy "requests_insert_self" on public.requests
for insert to authenticated
with check (auth.uid() = requester_id);

drop policy if exists "requests_update_owner" on public.requests;
create policy "requests_update_owner" on public.requests
for update to authenticated
using (auth.uid() = requester_id)
with check (auth.uid() = requester_id);

drop policy if exists "transactions_select_participant" on public.transactions;
create policy "transactions_select_participant" on public.transactions
for select to authenticated
using (auth.uid() = donor_id or auth.uid() = recipient_id);

drop policy if exists "notifications_select_owner" on public.notifications;
create policy "notifications_select_owner" on public.notifications
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "notifications_update_owner" on public.notifications;
create policy "notifications_update_owner" on public.notifications
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
